#!/bin/bash
# Security Deployment Script for CV Generator

echo "🔒 CV Generator Security Deployment"
echo "=================================="
echo ""
echo "📋 This script will deploy security updates to the production server"
echo ""
echo "Please run the following commands on the server (178.128.143.51):"
echo ""
echo "# 1. Connect to server"
echo "ssh claude@178.128.143.51"
echo ""
echo "# 2. Navigate to project"
echo "cd /var/www/cv-generator"
echo ""
echo "# 3. Pull latest changes"
echo "git pull origin main"
echo ""
echo "# 4. Install dependencies"
echo "npm install"
echo ""
echo "# 5. Generate secure API key"
echo "ANALYTICS_API_KEY=$(openssl rand -hex 32)"
echo "echo \"Generated API Key: \$ANALYTICS_API_KEY\""
echo ""
echo "# 6. Create production .env file"
echo "cat > .env << EOF"
echo "NODE_ENV=production"
echo "PORT=3000"
echo "ANALYTICS_API_KEY=\$ANALYTICS_API_KEY"
echo "CORS_ORIGIN=http://178.128.143.51,https://learningwithreda.com"
echo "API_ONLY=false"
echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable"
echo "EOF"
echo ""
echo "# 7. Set proper permissions"
echo "chmod 600 .env"
echo "chmod 600 analytics-data.json"
echo "chmod 600 daily-analytics.json"
echo ""
echo "# 8. Restart PM2 with new environment"
echo "pm2 delete cv-generator"
echo "pm2 start server.js --name cv-generator --env production"
echo "pm2 save"
echo "pm2 startup"
echo ""
echo "# 9. Test the deployment"
echo "curl -I http://localhost:3000/api/health"
echo "curl -X POST http://localhost:3000/api/analytics/track-view -H 'Content-Type: application/json' -d '{\"templateName\":\"modern\",\"sessionId\":\"test-deploy\"}'"
echo ""
echo "# 10. Check logs"
echo "pm2 logs cv-generator --lines 50"
echo ""
echo "🎯 After deployment, save the API key for admin access!"